# Generated by Django 5.2.6 on 2025-12-31 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="UserStaff",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Role",
                    models.IntegerField(
                        choices=[(1, "manager"), (2, "user")], default=1
                    ),
                ),
                (
                    "Team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DjangoApp.team",
                    ),
                ),
                (
                    "User",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="Manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DjangoApp.userstaff",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=120)),
                ("Description", models.TextField()),
                ("DateEnd", models.DateTimeField(auto_now=True)),
                (
                    "Status",
                    models.IntegerField(
                        choices=[(1, "new"), (2, "processing"), (3, "done")], default=1
                    ),
                ),
                (
                    "Team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DjangoApp.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DjangoApp.userstaff",
                    ),
                ),
            ],
        ),
    ]
