# Generated by Django 5.2.6 on 2025-12-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DjangoApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userstaff",
            old_name="User",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="task",
            name="DateEnd",
            field=models.DateTimeField(),
        ),
    ]
