# Generated by Django 6.0 on 2026-01-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DjangoApp", "0002_rename_user_userstaff_user_alter_task_dateend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="DateEnd",
            field=models.DateField(),
        ),
    ]
