# Generated by Django 5.2.8 on 2026-01-29 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DjangoApp", "0003_alter_task_dateend"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="Id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="Status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="Team",
            new_name="team",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="Title",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="Id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="userstaff",
            old_name="Id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="userstaff",
            old_name="Role",
            new_name="role",
        ),
        migrations.RemoveField(
            model_name="task",
            name="DateEnd",
        ),
        migrations.RemoveField(
            model_name="team",
            name="Manager",
        ),
        migrations.RemoveField(
            model_name="userstaff",
            name="Team",
        ),
        migrations.AddField(
            model_name="task",
            name="dateEnd",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="team",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_team",
                to="DjangoApp.userstaff",
            ),
        ),
        migrations.AddField(
            model_name="userstaff",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="DjangoApp.team",
            ),
        ),
    ]
